Makefile and Dockerfile fixes and improvements.
awslabs/aws-batch-cbmc pull request #16
Opened 2019-11-06 21:53 UTC by cmangla

Makefile fixes for CBMC (MiniSAT): Use wget as downloader.

Makefile improvements for AWS operations: Execute ECR login
automatically. Set aws region in Makefile.local

Dockerfile fixes: Add awscli dependencies.

2020-08-25 14:34 UTC, cmangla commented
@markrtuttle Would be great if you could review this one too.

2020-08-28 15:08 UTC, markrtuttle commented on Makefile
> +	@echo Attempting login to ECR
Logging into ECR...

2020-08-28 15:09 UTC, markrtuttle commented on Makefile
... done.

2020-08-28 15:12 UTC, markrtuttle commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends \
What has changed?  Why is this needed today and not yesterday?

2020-08-28 15:14 UTC, markrtuttle commented on pkg-batch/Makefile
> +	find $(BATCHOBJ) -maxdepth 0 -mindepth 0 -type f -not -name '.*' -exec cp -v '{}' $(BIN)/ \;
But there is nothing in the bin directory but python scripts.

2020-08-28 15:15 UTC, markrtuttle commented on pkg-viewer/Makefile
> +	# Copy files to BIN. Depth is 0 because of the '*' in VIEWEROBJ variable.
This directory contains only python scripts, why such a complicated solution?

2020-08-28 15:16 UTC, markrtuttle commented on pkg-cbmc/ubuntu16-cbmc/Makefile
> +	make DOWNLOADER='wget' -C $(CBMCGIT)/cbmc/src minisat2-download
I think wget is the default.

2020-08-28 16:30 UTC, cmangla commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends \
I seem to have always needed this, even back in October 2019.

2020-08-28 16:38 UTC, cmangla commented on pkg-batch/Makefile
> +	find $(BATCHOBJ) -maxdepth 0 -mindepth 0 -type f -not -name '.*' -exec cp -v '{}' $(BIN)/ \;
Out of the box, there is nothing else in the directory, except for the `.gitignore` file which is harmless. However, if you run any of the scripts locally, a `__pycache__` directory is created in there. If you forget to delete it before you run `make`, the `cp` command fails because it cannot copy the directory. The `-type f` in the command above ensures we try to only copy over files, and the depth limits ensure it does not recurse.

2020-08-28 16:41 UTC, cmangla commented on pkg-cbmc/ubuntu16-cbmc/Makefile
> +	make DOWNLOADER='wget' -C $(CBMCGIT)/cbmc/src minisat2-download
In the [CBMC Makefiles](https://github.com/diffblue/cbmc/blob/9ff9be8bed55a1b2f0ac9767b0848fbce4fd700e/src/Makefile#L117), the default is `lwp-download`, which is usually not there in the host by default.

2020-08-28 16:42 UTC, cmangla commented on pkg-viewer/Makefile
> +	# Copy files to BIN. Depth is 0 because of the '*' in VIEWEROBJ variable.
Out of the box, there is nothing else in the directory. However, if you run any of the scripts locally, a `__pycache__` directory is created in there. If you forget to delete it before you run make, the `cp` command fails because it cannot copy the directory. The `-type f` in the command above ensures we try to only copy over files, and the depth limits ensure it does not recurse.

2020-08-28 16:42 UTC, cmangla commented on Makefile
> +	@echo Attempting login to ECR
Will change

2020-08-28 16:42 UTC, cmangla commented on Makefile
Will add

2020-09-09 15:31 UTC, cmangla commented
@markrtuttle There is an issue with 'make login' . Please do not merge until I push another update.

2020-09-09 15:58 UTC, cmangla commented
> @markrtuttle There is an issue with 'make login' . Please do not merge until I push another update.

Should be fixed with latest commit

2020-09-09 23:02 UTC, markrtuttle requested changes
I just want to record that I've reviewed this pull request, but I have three concerns I want to look into before approving this.

2020-09-09 23:02 UTC, markrtuttle commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends \
I don't think this is right.  The packages libpython-dev, python-dev, and python-wheel are all libraries and development tools "for building Python
 modules, extending the Python interpreter or embedding Python in applications", none of that should be required by anything cbmc batch does.  I want to check into this.

2020-09-09 23:05 UTC, markrtuttle commented
@karkhaz @eidelmanjonathan I've left three unresolved comments on this pull request, could you look at them and advise on whether they have any merit?

2020-09-09 23:29 UTC, karkhaz commented on Makefile
> +	@echo $(LOGINPWD) | docker login --username AWS --password-stdin $(AWSID).dkr.ecr.$(AWSREGION).amazonaws.com
Suggest to combine the two rules into a single one, so that the password is entirely confined to this subshell. I don't see the need for a separate `loginpwd` rule. If the `ecr get-login-password` command fails, then nothing will be passed into `docker login` anyway, since the only output from `aws ecr` will be on stderr, so the whole thing will fail as expected.

2020-09-10 11:13 UTC, cmangla commented on Makefile
> +.PHONY: default install clean veryclean login loginpwd
Sorry about the `loginpwd` bit being left behind from the previous commit, will get rid of it in another commit.

2020-09-10 11:13 UTC, cmangla commented on Makefile
> +	$(eval LOGINPWD = $(shell aws ecr get-login-password --region $(AWSREGION)))
Latest commit resolves this issue, see comment below.

2020-09-10 11:14 UTC, cmangla commented on Makefile
> +	@echo $(LOGINPWD) | docker login --username AWS --password-stdin $(AWSID).dkr.ecr.$(AWSREGION).amazonaws.com
Latest commit resolves this issue, see comment below.

2020-09-10 11:27 UTC, cmangla commented
@markrtuttle @karkhaz The password can just be piped across in one line, as I have done in the latest commit, which should alleviate some security concerns. The console output looks like this:

```
| => make login
Logging into ECR ...
aws ecr get-login-password --region us-west-2 | \
		docker login --username AWS \
		--password-stdin \
		000000000000.dkr.ecr.us-west-2.amazonaws.com
Login Succeeded
```

I am working on fixing the Dockerfile issues.

2020-09-10 11:29 UTC, cmangla commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends \
I'm looking into this.

2020-09-10 13:09 UTC, cmangla commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends \
This is indeed excessive, but `python-wheel` and `python3-wheel` seem to be new requirements. Further below, the Dockerfile installs `awscli`. If Python wheel is not available, this error appears:
```
error: invalid command 'bdist_wheel'
```
Wheel can be removed after `awscli` install is complete.

2020-09-10 13:23 UTC, cmangla commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends \
Fixed in latest commit.

2020-09-10 13:37 UTC, markrtuttle approved these changes

2020-09-10 13:37 UTC, markrtuttle commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends python-wheel python3-wheel
You are correct.  Good catch.  Please move these python wheel packages to the list of other python setuptools packages (the other python package building tools) so they are installed in the same docker layer with a single apt-get install.  Please consider adding a comment before this apt-get install saying "Include ubuntu packages to build python packages, because the pip installation of awscli tries to build wheel packages for awscli, pyyaml, and boto3."  Then I will approve this pull request.

2020-09-10 14:05 UTC, cmangla commented on docker/ubuntu16-gcc/Dockerfile
> +RUN apt-get -y install --no-install-recommends python-wheel python3-wheel
Fixed in latest commit.

2020-09-10 14:10 UTC, markrtuttle approved these changes

2020-09-10 14:11 UTC, merged